# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gp5CIFOGuzueGp8TVjv06WarWgzL529t
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,8])
y=np.array([0,350])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,2,4,5,7,8])
y=np.array([2,8,2,8,2,8])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

y=np.array([2,8,3,9,1,7])
plt.plot(y,marker='o')
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,2,4,6,8])
y=np.array([0,2,4,6,8])
mycolor=['red','green','lime','aqua','yellow']
size=[100,300,500,700,900]
plt.scatter(x,y,color=mycolor,s=size)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['614','613','510'])
y=np.array([22,25,18])
plt.bar(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array(['614','613','510'])
y=np.array([22,25,18])
plt.barh(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([15,25,35,15,10])

plt.pie(x)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([15,25,35,15,10])
mylabels=["1-yil","2-yil","3-yil","4-yil","5-yil"]

plt.pie(x,labels=mylabels)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([15,25,35,15,10])
mylabels=["1-yil","2-yil","3-yil","4-yil","5-yil"]

myexplode=[0.2,0,0,0,0]

plt.pie(x,labels=mylabels,startangle=90,explode=myexplode)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([15,25,35,15,10])
mylabels=["1-yil","2-yil","3-yil","4-yil","5-yil"]

myexplode=[0.2,0,0,0,0]

plt.pie(x,labels=mylabels,startangle=90,explode=myexplode,shadow=True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([15,25,35,15,10])
mylabels=["1-yil","2-yil","3-yil","4-yil","5-yil"]

plt.pie(x,labels=mylabels)
plt.legend()
plt.show()